version: '2'
services:
  mysql:
    image: mysql:5.7.14
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "kplcloud"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]
    expose:
      - "3306"
    ports:
      - "3306:3306"
  redis:
      image: redis
      expose:
        - "6379"
      ports:
        - "6379:6379"
      volumes:
        - ./redis-data:/data
  rabbitmq:
    environment:
      RABBITMQ_NODENAME: "rabbitmq"
      RABBITMQ_DEFAULT_USER: "kplcloud"
      RABBITMQ_DEFAULT_PASS: "kplcloud"
    image: rabbitmq:3.6.14-management-alpine
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"

